/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Enumeration das ações de alteração da proposta.
    /// </summary>
    /// <value>Enumeration das ações de alteração da proposta.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum AcaoAlteracaoProposta
    {

        /// <summary>
        /// Enum CANCELAMENTO for value: CANCELAMENTO
        /// </summary>


        [EnumMember(Value = "CANCELAMENTO")]
        CANCELAMENTO = 1,

        /// <summary>
        /// Enum EFETIVACAO for value: EFETIVACAO
        /// </summary>


        [EnumMember(Value = "EFETIVACAO")]
        EFETIVACAO = 2,

        /// <summary>
        /// Enum PREEFETIVACAO for value: PRE_EFETIVACAO
        /// </summary>

        [EnumMember(Value = "PRE_EFETIVACAO")]
        PREEFETIVACAO = 3,

        /// <summary>
        /// Enum ATUALIZACAO for value: ATUALIZACAO
        /// </summary>

        [EnumMember(Value = "ATUALIZACAO ")]
        ATUALIZACAO = 4
    }

}
