/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Entidade contendo CPF e um documento binário da proposta.
    /// </summary>
    [DataContract]
    public partial class CpfDocumentoProposta :  IEquatable<CpfDocumentoProposta>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CpfDocumentoProposta" /> class.
        /// </summary>
        /// <param name="Cpf">CPF do operador..</param>
        /// <param name="Documento">Conteúdo do arquivo em binário..</param>
        /// <param name="Extensao">Extensão do arquivo..</param>
        public CpfDocumentoProposta(string Cpf = default(string), byte[] Documento = default(byte[]), string Extensao = default(string))
        {
            this.Cpf = Cpf;
            this.Documento = Documento;
            this.Extensao = Extensao;
        }
        
        /// <summary>
        /// CPF do operador.
        /// </summary>
        /// <value>CPF do operador.</value>
        [DataMember(Name="cpf", EmitDefaultValue=false)]
        public string Cpf { get; set; }

        /// <summary>
        /// Conteúdo do arquivo em binário.
        /// </summary>
        /// <value>Conteúdo do arquivo em binário.</value>
        [DataMember(Name="documento", EmitDefaultValue=false)]
        public byte[] Documento { get; set; }

        /// <summary>
        /// Extensão do arquivo.
        /// </summary>
        /// <value>Extensão do arquivo.</value>
        [DataMember(Name="extensao", EmitDefaultValue=false)]
        public string Extensao { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CpfDocumentoProposta {\n");
            sb.Append("  Cpf: ").Append(Cpf).Append("\n");
            sb.Append("  Documento: ").Append(Documento).Append("\n");
            sb.Append("  Extensao: ").Append(Extensao).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CpfDocumentoProposta);
        }

        /// <summary>
        /// Returns true if CpfDocumentoProposta instances are equal
        /// </summary>
        /// <param name="input">Instance of CpfDocumentoProposta to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CpfDocumentoProposta input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Cpf == input.Cpf ||
                    (this.Cpf != null &&
                    this.Cpf.Equals(input.Cpf))
                ) && 
                (
                    this.Documento == input.Documento ||
                    (this.Documento != null &&
                    this.Documento.Equals(input.Documento))
                ) && 
                (
                    this.Extensao == input.Extensao ||
                    (this.Extensao != null &&
                    this.Extensao.Equals(input.Extensao))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Cpf != null)
                    hashCode = hashCode * 59 + this.Cpf.GetHashCode();
                if (this.Documento != null)
                    hashCode = hashCode * 59 + this.Documento.GetHashCode();
                if (this.Extensao != null)
                    hashCode = hashCode * 59 + this.Extensao.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
