/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Entidade representando informações adicionais da proposta.
    /// </summary>
    [DataContract]
    public partial class DadoAdicional :  IEquatable<DadoAdicional>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DadoAdicional" /> class.
        /// </summary>
        /// <param name="Campo">Campo da informação..</param>
        /// <param name="Valor">Valor da informação..</param>
        public DadoAdicional(string Campo = default(string), string Valor = default(string))
        {
            this.Campo = Campo;
            this.Valor = Valor;
        }
        
        /// <summary>
        /// Campo da informação.
        /// </summary>
        /// <value>Campo da informação.</value>
        [DataMember(Name="campo", EmitDefaultValue=false)]
        public string Campo { get; set; }

        /// <summary>
        /// Valor da informação.
        /// </summary>
        /// <value>Valor da informação.</value>
        [DataMember(Name="valor", EmitDefaultValue=false)]
        public string Valor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DadoAdicional {\n");
            sb.Append("  Campo: ").Append(Campo).Append("\n");
            sb.Append("  Valor: ").Append(Valor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DadoAdicional);
        }

        /// <summary>
        /// Returns true if DadoAdicional instances are equal
        /// </summary>
        /// <param name="input">Instance of DadoAdicional to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DadoAdicional input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Campo == input.Campo ||
                    (this.Campo != null &&
                    this.Campo.Equals(input.Campo))
                ) && 
                (
                    this.Valor == input.Valor ||
                    (this.Valor != null &&
                    this.Valor.Equals(input.Valor))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Campo != null)
                    hashCode = hashCode * 59 + this.Campo.GetHashCode();
                if (this.Valor != null)
                    hashCode = hashCode * 59 + this.Valor.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
