/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Enumeration dos estados civil de cliente.
    /// </summary>
    /// <value>Enumeration dos estados civil de cliente.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum EstadoCivil
    {
        
        /// <summary>
        /// Enum CASADO for value: CASADO
        /// </summary>
        [EnumMember(Value = "CASADO")]
        CASADO = 1,
        
        /// <summary>
        /// Enum DIVORCIADO for value: DIVORCIADO
        /// </summary>
        [EnumMember(Value = "DIVORCIADO")]
        DIVORCIADO = 2,
        
        /// <summary>
        /// Enum SEPARADOJUDICIALMENTE for value: SEPARADO_JUDICIALMENTE
        /// </summary>
        [EnumMember(Value = "SEPARADO_JUDICIALMENTE")]
        SEPARADOJUDICIALMENTE = 3,
        
        /// <summary>
        /// Enum OUTROS for value: OUTROS
        /// </summary>
        [EnumMember(Value = "OUTROS")]
        OUTROS = 4,
        
        /// <summary>
        /// Enum COMPANHEIRO for value: COMPANHEIRO
        /// </summary>
        [EnumMember(Value = "COMPANHEIRO")]
        COMPANHEIRO = 5,
        
        /// <summary>
        /// Enum SOLTEIRO for value: SOLTEIRO
        /// </summary>
        [EnumMember(Value = "SOLTEIRO")]
        SOLTEIRO = 6,
        
        /// <summary>
        /// Enum VIUVO for value: VIUVO
        /// </summary>
        [EnumMember(Value = "VIUVO")]
        VIUVO = 7
    }

}
