/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Entidade que representa uma renda adicional
    /// </summary>
    [DataContract]
    public partial class RendaAdicional :  IEquatable<RendaAdicional>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RendaAdicional" /> class.
        /// </summary>
        /// <param name="Valor">Valor da renda adicional..</param>
        /// <param name="Cnpj">CNPJ da empresa..</param>
        /// <param name="DataAdmissao">Data da admissão. (aaaa-mm-dd)..</param>
        /// <param name="NomeEmpresa">Nome da empresa..</param>
        /// <param name="NumeroBeneficio">Número do benefício..</param>
        /// <param name="EspecieBeneficio">Espécie do benefício..</param>
        /// <param name="Telefones">Telefones.</param>
        /// <param name="Endereco">Endereco.</param>
        public RendaAdicional(double? Valor = default(double?), string Cnpj = default(string), DateTime? DataAdmissao = default(DateTime?), string NomeEmpresa = default(string), string NumeroBeneficio = default(string), string EspecieBeneficio = default(string), List<Telefone> Telefones = default(List<Telefone>), Endereco Endereco = default(Endereco))
        {
            this.Valor = Valor;
            this.Cnpj = Cnpj;
            this.DataAdmissao = DataAdmissao;
            this.NomeEmpresa = NomeEmpresa;
            this.NumeroBeneficio = NumeroBeneficio;
            this.EspecieBeneficio = EspecieBeneficio;
            this.Telefones = Telefones;
            this.Endereco = Endereco;
        }
        
        /// <summary>
        /// Valor da renda adicional.
        /// </summary>
        /// <value>Valor da renda adicional.</value>
        [DataMember(Name="valor", EmitDefaultValue=false)]
        public double? Valor { get; set; }

        /// <summary>
        /// CNPJ da empresa.
        /// </summary>
        /// <value>CNPJ da empresa.</value>
        [DataMember(Name="cnpj", EmitDefaultValue=false)]
        public string Cnpj { get; set; }

        /// <summary>
        /// Data da admissão. (aaaa-mm-dd).
        /// </summary>
        /// <value>Data da admissão. (aaaa-mm-dd).</value>
        [DataMember(Name="dataAdmissao", EmitDefaultValue=false)]
        [JsonConverter(typeof(SwaggerDateConverter))]
        public DateTime? DataAdmissao { get; set; }

        /// <summary>
        /// Nome da empresa.
        /// </summary>
        /// <value>Nome da empresa.</value>
        [DataMember(Name="nomeEmpresa", EmitDefaultValue=false)]
        public string NomeEmpresa { get; set; }

        /// <summary>
        /// Número do benefício.
        /// </summary>
        /// <value>Número do benefício.</value>
        [DataMember(Name="numeroBeneficio", EmitDefaultValue=false)]
        public string NumeroBeneficio { get; set; }

        /// <summary>
        /// Espécie do benefício.
        /// </summary>
        /// <value>Espécie do benefício.</value>
        [DataMember(Name="especieBeneficio", EmitDefaultValue=false)]
        public string EspecieBeneficio { get; set; }

        /// <summary>
        /// Gets or Sets Telefones
        /// </summary>
        [DataMember(Name="telefones", EmitDefaultValue=false)]
        public List<Telefone> Telefones { get; set; }

        /// <summary>
        /// Gets or Sets Endereco
        /// </summary>
        [DataMember(Name="endereco", EmitDefaultValue=false)]
        public Endereco Endereco { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RendaAdicional {\n");
            sb.Append("  Valor: ").Append(Valor).Append("\n");
            sb.Append("  Cnpj: ").Append(Cnpj).Append("\n");
            sb.Append("  DataAdmissao: ").Append(DataAdmissao).Append("\n");
            sb.Append("  NomeEmpresa: ").Append(NomeEmpresa).Append("\n");
            sb.Append("  NumeroBeneficio: ").Append(NumeroBeneficio).Append("\n");
            sb.Append("  EspecieBeneficio: ").Append(EspecieBeneficio).Append("\n");
            sb.Append("  Telefones: ").Append(Telefones).Append("\n");
            sb.Append("  Endereco: ").Append(Endereco).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RendaAdicional);
        }

        /// <summary>
        /// Returns true if RendaAdicional instances are equal
        /// </summary>
        /// <param name="input">Instance of RendaAdicional to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RendaAdicional input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Valor == input.Valor ||
                    (this.Valor != null &&
                    this.Valor.Equals(input.Valor))
                ) && 
                (
                    this.Cnpj == input.Cnpj ||
                    (this.Cnpj != null &&
                    this.Cnpj.Equals(input.Cnpj))
                ) && 
                (
                    this.DataAdmissao == input.DataAdmissao ||
                    (this.DataAdmissao != null &&
                    this.DataAdmissao.Equals(input.DataAdmissao))
                ) && 
                (
                    this.NomeEmpresa == input.NomeEmpresa ||
                    (this.NomeEmpresa != null &&
                    this.NomeEmpresa.Equals(input.NomeEmpresa))
                ) && 
                (
                    this.NumeroBeneficio == input.NumeroBeneficio ||
                    (this.NumeroBeneficio != null &&
                    this.NumeroBeneficio.Equals(input.NumeroBeneficio))
                ) && 
                (
                    this.EspecieBeneficio == input.EspecieBeneficio ||
                    (this.EspecieBeneficio != null &&
                    this.EspecieBeneficio.Equals(input.EspecieBeneficio))
                ) && 
                (
                    this.Telefones == input.Telefones ||
                    this.Telefones != null &&
                    this.Telefones.SequenceEqual(input.Telefones)
                ) && 
                (
                    this.Endereco == input.Endereco ||
                    (this.Endereco != null &&
                    this.Endereco.Equals(input.Endereco))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Valor != null)
                    hashCode = hashCode * 59 + this.Valor.GetHashCode();
                if (this.Cnpj != null)
                    hashCode = hashCode * 59 + this.Cnpj.GetHashCode();
                if (this.DataAdmissao != null)
                    hashCode = hashCode * 59 + this.DataAdmissao.GetHashCode();
                if (this.NomeEmpresa != null)
                    hashCode = hashCode * 59 + this.NomeEmpresa.GetHashCode();
                if (this.NumeroBeneficio != null)
                    hashCode = hashCode * 59 + this.NumeroBeneficio.GetHashCode();
                if (this.EspecieBeneficio != null)
                    hashCode = hashCode * 59 + this.EspecieBeneficio.GetHashCode();
                if (this.Telefones != null)
                    hashCode = hashCode * 59 + this.Telefones.GetHashCode();
                if (this.Endereco != null)
                    hashCode = hashCode * 59 + this.Endereco.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
