/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Enumeration dos tipos de sexo.
    /// </summary>
    /// <value>Enumeration dos tipos de sexo.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum Sexo
    {
        
        /// <summary>
        /// Enum MASCULINO for value: MASCULINO
        /// </summary>
        [EnumMember(Value = "MASCULINO")]
        MASCULINO = 1,
        
        /// <summary>
        /// Enum FEMININO for value: FEMININO
        /// </summary>
        [EnumMember(Value = "FEMININO")]
        FEMININO = 2
    }

}
