/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Entidade representando um telefone.
    /// </summary>
    [DataContract]
    public partial class Telefone :  IEquatable<Telefone>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets Tipo
        /// </summary>
        [DataMember(Name="tipo", EmitDefaultValue=false)]
        public TipoTelefone? Tipo { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Telefone" /> class.
        /// </summary>
        /// <param name="Tipo">Tipo.</param>
        /// <param name="Ddd">Código de discagem direta a distância..</param>
        /// <param name="Numero">Número do telefone..</param>
        /// <param name="Ramal">Ramal do telefone..</param>
        public Telefone(TipoTelefone? Tipo = default(TipoTelefone?), string Ddd = default(string), string Numero = default(string), string Ramal = default(string))
        {
            this.Tipo = Tipo;
            this.Ddd = Ddd;
            this.Numero = Numero;
            this.Ramal = Ramal;
        }
        

        /// <summary>
        /// Código de discagem direta a distância.
        /// </summary>
        /// <value>Código de discagem direta a distância.</value>
        [DataMember(Name="ddd", EmitDefaultValue=false)]
        public string Ddd { get; set; }

        /// <summary>
        /// Número do telefone.
        /// </summary>
        /// <value>Número do telefone.</value>
        [DataMember(Name="numero", EmitDefaultValue=false)]
        public string Numero { get; set; }

        /// <summary>
        /// Ramal do telefone.
        /// </summary>
        /// <value>Ramal do telefone.</value>
        [DataMember(Name="ramal", EmitDefaultValue=false)]
        public string Ramal { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Telefone {\n");
            sb.Append("  Tipo: ").Append(Tipo).Append("\n");
            sb.Append("  Ddd: ").Append(Ddd).Append("\n");
            sb.Append("  Numero: ").Append(Numero).Append("\n");
            sb.Append("  Ramal: ").Append(Ramal).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Telefone);
        }

        /// <summary>
        /// Returns true if Telefone instances are equal
        /// </summary>
        /// <param name="input">Instance of Telefone to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Telefone input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Tipo == input.Tipo ||
                    (this.Tipo != null &&
                    this.Tipo.Equals(input.Tipo))
                ) && 
                (
                    this.Ddd == input.Ddd ||
                    (this.Ddd != null &&
                    this.Ddd.Equals(input.Ddd))
                ) && 
                (
                    this.Numero == input.Numero ||
                    (this.Numero != null &&
                    this.Numero.Equals(input.Numero))
                ) && 
                (
                    this.Ramal == input.Ramal ||
                    (this.Ramal != null &&
                    this.Ramal.Equals(input.Ramal))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Tipo != null)
                    hashCode = hashCode * 59 + this.Tipo.GetHashCode();
                if (this.Ddd != null)
                    hashCode = hashCode * 59 + this.Ddd.GetHashCode();
                if (this.Numero != null)
                    hashCode = hashCode * 59 + this.Numero.GetHashCode();
                if (this.Ramal != null)
                    hashCode = hashCode * 59 + this.Ramal.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
