/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Enumeration dos tipos de contas.
    /// </summary>
    /// <value>Enumeration dos tipos de contas.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum TipoConta
    {
        
        /// <summary>
        /// Enum CHEQUEESPECIAL for value: CHEQUE_ESPECIAL
        /// </summary>
        [EnumMember(Value = "CHEQUE_ESPECIAL")]
        CHEQUEESPECIAL = 1,
        
        /// <summary>
        /// Enum CONTASIMPLES for value: CONTA_SIMPLES
        /// </summary>
        [EnumMember(Value = "CONTA_SIMPLES")]
        CONTASIMPLES = 2
    }

}
