/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Enumeration dos tipos de correspondência do endereço.
    /// </summary>
    /// <value>Enumeration dos tipos de correspondência do endereço.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum TipoCorrespondencia
    {
        
        /// <summary>
        /// Enum COMERCIAL for value: COMERCIAL
        /// </summary>
        [EnumMember(Value = "COMERCIAL")]
        COMERCIAL = 1,
        
        /// <summary>
        /// Enum RESIDENCIAL for value: RESIDENCIAL
        /// </summary>
        [EnumMember(Value = "RESIDENCIAL")]
        RESIDENCIAL = 2
    }

}
