/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Enumeration dos tipos de seguro.
    /// </summary>
    /// <value>Enumeration dos tipos de seguro.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum TipoSeguro
    {
        
        /// <summary>
        /// Enum SEMSEGURO for value: SEM_SEGURO
        /// </summary>
        [EnumMember(Value = "SEM_SEGURO")]
        SEMSEGURO = 1,
        
        /// <summary>
        /// Enum SEGUROBASICO for value: SEGURO_BASICO
        /// </summary>
        [EnumMember(Value = "SEGURO_BASICO")]
        SEGUROBASICO = 2,
        
        /// <summary>
        /// Enum SEGUROCOMPLETO for value: SEGURO_COMPLETO
        /// </summary>
        [EnumMember(Value = "SEGURO_COMPLETO")]
        SEGUROCOMPLETO = 3
    }

}
