/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Enumeration dos tipos de residência do endereço.
    /// </summary>
    /// <value>Enumeration dos tipos de residência do endereço.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum TipoResidencia
    {
        
        /// <summary>
        /// Enum PROPRIAQUITADA for value: PROPRIA_QUITADA
        /// </summary>
        [EnumMember(Value = "PROPRIA_QUITADA")]
        PROPRIAQUITADA = 1,
        
        /// <summary>
        /// Enum PROPRIAFINANCIADA for value: PROPRIA_FINANCIADA
        /// </summary>
        [EnumMember(Value = "PROPRIA_FINANCIADA")]
        PROPRIAFINANCIADA = 2,
        
        /// <summary>
        /// Enum ALUGADA for value: ALUGADA
        /// </summary>
        [EnumMember(Value = "ALUGADA")]
        ALUGADA = 3,
        
        /// <summary>
        /// Enum PARENTES for value: PARENTES
        /// </summary>
        [EnumMember(Value = "PARENTES")]
        PARENTES = 4,
        
        /// <summary>
        /// Enum FUNCIONAL for value: FUNCIONAL
        /// </summary>
        [EnumMember(Value = "FUNCIONAL")]
        FUNCIONAL = 5,
        
        /// <summary>
        /// Enum OUTROS for value: OUTROS
        /// </summary>
        [EnumMember(Value = "OUTROS")]
        OUTROS = 6
    }

}
