/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Enumeration dos tipos de telefone.
    /// </summary>
    /// <value>Enumeration dos tipos de telefone.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum TipoTelefone
    {
        
        /// <summary>
        /// Enum FIXO for value: FIXO
        /// </summary>
        [EnumMember(Value = "FIXO")]
        FIXO = 1,
        
        /// <summary>
        /// Enum CELULAR for value: CELULAR
        /// </summary>
        [EnumMember(Value = "CELULAR")]
        CELULAR = 2,
        
        /// <summary>
        /// Enum RECADOS for value: RECADOS
        /// </summary>
        [EnumMember(Value = "RECADOS")]
        RECADOS = 3
    }

}
