/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Enumeration dos tipos de efetivações para a proposta.
    /// </summary>
    /// <value>Enumeration dos tipos de efetivações para a proposta.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum TipoEfetivacao
    {
        
        /// <summary>
        /// Enum LOJA for value: LOJA
        /// </summary>
        [EnumMember(Value = "LOJA")]
        LOJA = 1,
        
        /// <summary>
        /// Enum DELIVERY for value: DELIVERY
        /// </summary>
        [EnumMember(Value = "DELIVERY")]
        DELIVERY = 2
    }

}
