/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Enumeration dos tipos de conta bancária.
    /// </summary>
    /// <value>Enumeration dos tipos de conta bancária.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum TipoContaBancaria
    {
        
        /// <summary>
        /// Enum CORRENTEPF for value: CONTA_CORRENTE_PF
        /// </summary>
        [EnumMember(Value = "CONTA_CORRENTE_PF")]
        CORRENTEPF = 1,
        
        /// <summary>
        /// Enum POUPANCAPF for value: CONTA_POUPANCA_PF
        /// </summary>
        [EnumMember(Value = "CONTA_POUPANCA_PF")]
        POUPANCAPF = 2,
        
        /// <summary>
        /// Enum FACILPFCEF for value: CONTA_FACIL_PF_CEF
        /// </summary>
        [EnumMember(Value = "CONTA_FACIL_PF_CEF")]
        FACILPFCEF = 3,
        
        /// <summary>
        /// Enum SALARIOPF for value: CONTA_SALARIO_PF
        /// </summary>
        [EnumMember(Value = "CONTA_SALARIO_PF")]
        SALARIOPF = 4,
        
        /// <summary>
        /// Enum CORRENTEPJ for value: CONTA_CORRENTE_PJ
        /// </summary>
        [EnumMember(Value = "CONTA_CORRENTE_PJ")]
        CORRENTEPJ = 5,
        
        /// <summary>
        /// Enum POUPANCAPJ for value: CONTA_POUPANCA_PJ
        /// </summary>
        [EnumMember(Value = "CONTA_POUPANCA_PJ")]
        POUPANCAPJ = 6
    }

}
