/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AlteracaoPropostaRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AlteracaoPropostaRequestTests
    {
        // TODO uncomment below to declare an instance variable for AlteracaoPropostaRequest
        //private AlteracaoPropostaRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AlteracaoPropostaRequest
            //instance = new AlteracaoPropostaRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AlteracaoPropostaRequest
        /// </summary>
        [Test]
        public void AlteracaoPropostaRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AlteracaoPropostaRequest
            //Assert.IsInstanceOfType<AlteracaoPropostaRequest> (instance, "variable 'instance' is a AlteracaoPropostaRequest");
        }


        /// <summary>
        /// Test the property 'AcaoAlteracao'
        /// </summary>
        [Test]
        public void AcaoAlteracaoTest()
        {
            // TODO unit test for the property 'AcaoAlteracao'
        }
        /// <summary>
        /// Test the property 'UploadConfirmado'
        /// </summary>
        [Test]
        public void UploadConfirmadoTest()
        {
            // TODO unit test for the property 'UploadConfirmado'
        }
        /// <summary>
        /// Test the property 'PreEfetivacaoProposta'
        /// </summary>
        [Test]
        public void PreEfetivacaoPropostaTest()
        {
            // TODO unit test for the property 'PreEfetivacaoProposta'
        }
        /// <summary>
        /// Test the property 'Proposta'
        /// </summary>
        [Test]
        public void PropostaTest()
        {
            // TODO unit test for the property 'Proposta'
        }

    }

}
