/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Candidato
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CandidatoTests
    {
        // TODO uncomment below to declare an instance variable for Candidato
        //private Candidato instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Candidato
            //instance = new Candidato();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Candidato
        /// </summary>
        [Test]
        public void CandidatoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Candidato
            //Assert.IsInstanceOfType<Candidato> (instance, "variable 'instance' is a Candidato");
        }


        /// <summary>
        /// Test the property 'Cpf'
        /// </summary>
        [Test]
        public void CpfTest()
        {
            // TODO unit test for the property 'Cpf'
        }

    }

}
