/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CartaoCredito
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CartaoCreditoTests
    {
        // TODO uncomment below to declare an instance variable for CartaoCredito
        //private CartaoCredito instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CartaoCredito
            //instance = new CartaoCredito();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CartaoCredito
        /// </summary>
        [Test]
        public void CartaoCreditoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CartaoCredito
            //Assert.IsInstanceOfType<CartaoCredito> (instance, "variable 'instance' is a CartaoCredito");
        }


        /// <summary>
        /// Test the property 'Emissor'
        /// </summary>
        [Test]
        public void EmissorTest()
        {
            // TODO unit test for the property 'Emissor'
        }
        /// <summary>
        /// Test the property 'LimiteCredito'
        /// </summary>
        [Test]
        public void LimiteCreditoTest()
        {
            // TODO unit test for the property 'LimiteCredito'
        }

    }

}
