/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Cheque
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChequeTests
    {
        // TODO uncomment below to declare an instance variable for Cheque
        //private Cheque instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Cheque
            //instance = new Cheque();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Cheque
        /// </summary>
        [Test]
        public void ChequeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Cheque
            //Assert.IsInstanceOfType<Cheque> (instance, "variable 'instance' is a Cheque");
        }


        /// <summary>
        /// Test the property 'Cmc7'
        /// </summary>
        [Test]
        public void Cmc7Test()
        {
            // TODO unit test for the property 'Cmc7'
        }
        /// <summary>
        /// Test the property 'Parcela'
        /// </summary>
        [Test]
        public void ParcelaTest()
        {
            // TODO unit test for the property 'Parcela'
        }
        /// <summary>
        /// Test the property 'Vencimento'
        /// </summary>
        [Test]
        public void VencimentoTest()
        {
            // TODO unit test for the property 'Vencimento'
        }

    }

}
