/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Cliente
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ClienteTests
    {
        // TODO uncomment below to declare an instance variable for Cliente
        //private Cliente instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Cliente
            //instance = new Cliente();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Cliente
        /// </summary>
        [Test]
        public void ClienteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Cliente
            //Assert.IsInstanceOfType<Cliente> (instance, "variable 'instance' is a Cliente");
        }


        /// <summary>
        /// Test the property 'Nome'
        /// </summary>
        [Test]
        public void NomeTest()
        {
            // TODO unit test for the property 'Nome'
        }
        /// <summary>
        /// Test the property 'Cpf'
        /// </summary>
        [Test]
        public void CpfTest()
        {
            // TODO unit test for the property 'Cpf'
        }
        /// <summary>
        /// Test the property 'DataNascimento'
        /// </summary>
        [Test]
        public void DataNascimentoTest()
        {
            // TODO unit test for the property 'DataNascimento'
        }
        /// <summary>
        /// Test the property 'NumeroDependentes'
        /// </summary>
        [Test]
        public void NumeroDependentesTest()
        {
            // TODO unit test for the property 'NumeroDependentes'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'CodigoEscolaridade'
        /// </summary>
        [Test]
        public void CodigoEscolaridadeTest()
        {
            // TODO unit test for the property 'CodigoEscolaridade'
        }
        /// <summary>
        /// Test the property 'NomeMae'
        /// </summary>
        [Test]
        public void NomeMaeTest()
        {
            // TODO unit test for the property 'NomeMae'
        }
        /// <summary>
        /// Test the property 'NomePai'
        /// </summary>
        [Test]
        public void NomePaiTest()
        {
            // TODO unit test for the property 'NomePai'
        }
        /// <summary>
        /// Test the property 'Cidade'
        /// </summary>
        [Test]
        public void CidadeTest()
        {
            // TODO unit test for the property 'Cidade'
        }
        /// <summary>
        /// Test the property 'Uf'
        /// </summary>
        [Test]
        public void UfTest()
        {
            // TODO unit test for the property 'Uf'
        }
        /// <summary>
        /// Test the property 'Tipo'
        /// </summary>
        [Test]
        public void TipoTest()
        {
            // TODO unit test for the property 'Tipo'
        }
        /// <summary>
        /// Test the property 'Documentos'
        /// </summary>
        [Test]
        public void DocumentosTest()
        {
            // TODO unit test for the property 'Documentos'
        }
        /// <summary>
        /// Test the property 'EstadoCivil'
        /// </summary>
        [Test]
        public void EstadoCivilTest()
        {
            // TODO unit test for the property 'EstadoCivil'
        }
        /// <summary>
        /// Test the property 'Nacionalidade'
        /// </summary>
        [Test]
        public void NacionalidadeTest()
        {
            // TODO unit test for the property 'Nacionalidade'
        }
        /// <summary>
        /// Test the property 'Sexo'
        /// </summary>
        [Test]
        public void SexoTest()
        {
            // TODO unit test for the property 'Sexo'
        }
        /// <summary>
        /// Test the property 'Telefones'
        /// </summary>
        [Test]
        public void TelefonesTest()
        {
            // TODO unit test for the property 'Telefones'
        }
        /// <summary>
        /// Test the property 'Conjuge'
        /// </summary>
        [Test]
        public void ConjugeTest()
        {
            // TODO unit test for the property 'Conjuge'
        }
        /// <summary>
        /// Test the property 'Emprego'
        /// </summary>
        [Test]
        public void EmpregoTest()
        {
            // TODO unit test for the property 'Emprego'
        }
        /// <summary>
        /// Test the property 'Enderecos'
        /// </summary>
        [Test]
        public void EnderecosTest()
        {
            // TODO unit test for the property 'Enderecos'
        }
        /// <summary>
        /// Test the property 'RendasAdicionais'
        /// </summary>
        [Test]
        public void RendasAdicionaisTest()
        {
            // TODO unit test for the property 'RendasAdicionais'
        }
        /// <summary>
        /// Test the property 'Negativado'
        /// </summary>
        [Test]
        public void NegativadoTest()
        {
            // TODO unit test for the property 'Negativado'
        }
        /// <summary>
        /// Test the property 'PossuiCheque'
        /// </summary>
        [Test]
        public void PossuiChequeTest()
        {
            // TODO unit test for the property 'PossuiCheque'
        }
        /// <summary>
        /// Test the property 'ContasBancarias'
        /// </summary>
        [Test]
        public void ContasBancariasTest()
        {
            // TODO unit test for the property 'ContasBancarias'
        }
        /// <summary>
        /// Test the property 'CartoesCredito'
        /// </summary>
        [Test]
        public void CartoesCreditoTest()
        {
            // TODO unit test for the property 'CartoesCredito'
        }
        /// <summary>
        /// Test the property 'ReferenciasPessoais'
        /// </summary>
        [Test]
        public void ReferenciasPessoaisTest()
        {
            // TODO unit test for the property 'ReferenciasPessoais'
        }

    }

}
