/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Conjuge
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConjugeTests
    {
        // TODO uncomment below to declare an instance variable for Conjuge
        //private Conjuge instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Conjuge
            //instance = new Conjuge();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Conjuge
        /// </summary>
        [Test]
        public void ConjugeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Conjuge
            //Assert.IsInstanceOfType<Conjuge> (instance, "variable 'instance' is a Conjuge");
        }


        /// <summary>
        /// Test the property 'Cpf'
        /// </summary>
        [Test]
        public void CpfTest()
        {
            // TODO unit test for the property 'Cpf'
        }
        /// <summary>
        /// Test the property 'DataNascimento'
        /// </summary>
        [Test]
        public void DataNascimentoTest()
        {
            // TODO unit test for the property 'DataNascimento'
        }
        /// <summary>
        /// Test the property 'Nome'
        /// </summary>
        [Test]
        public void NomeTest()
        {
            // TODO unit test for the property 'Nome'
        }
        /// <summary>
        /// Test the property 'Emprego'
        /// </summary>
        [Test]
        public void EmpregoTest()
        {
            // TODO unit test for the property 'Emprego'
        }

    }

}
