/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ContaBancaria
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ContaBancariaTests
    {
        // TODO uncomment below to declare an instance variable for ContaBancaria
        //private ContaBancaria instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ContaBancaria
            //instance = new ContaBancaria();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContaBancaria
        /// </summary>
        [Test]
        public void ContaBancariaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ContaBancaria
            //Assert.IsInstanceOfType<ContaBancaria> (instance, "variable 'instance' is a ContaBancaria");
        }


        /// <summary>
        /// Test the property 'CodigoBanco'
        /// </summary>
        [Test]
        public void CodigoBancoTest()
        {
            // TODO unit test for the property 'CodigoBanco'
        }
        /// <summary>
        /// Test the property 'TipoContaBancaria'
        /// </summary>
        [Test]
        public void TipoContaBancariaTest()
        {
            // TODO unit test for the property 'TipoContaBancaria'
        }
        /// <summary>
        /// Test the property 'CodigoAgencia'
        /// </summary>
        [Test]
        public void CodigoAgenciaTest()
        {
            // TODO unit test for the property 'CodigoAgencia'
        }
        /// <summary>
        /// Test the property 'Conta'
        /// </summary>
        [Test]
        public void ContaTest()
        {
            // TODO unit test for the property 'Conta'
        }
        /// <summary>
        /// Test the property 'Cidade'
        /// </summary>
        [Test]
        public void CidadeTest()
        {
            // TODO unit test for the property 'Cidade'
        }
        /// <summary>
        /// Test the property 'Uf'
        /// </summary>
        [Test]
        public void UfTest()
        {
            // TODO unit test for the property 'Uf'
        }
        /// <summary>
        /// Test the property 'TempoMes'
        /// </summary>
        [Test]
        public void TempoMesTest()
        {
            // TODO unit test for the property 'TempoMes'
        }
        /// <summary>
        /// Test the property 'TempoAno'
        /// </summary>
        [Test]
        public void TempoAnoTest()
        {
            // TODO unit test for the property 'TempoAno'
        }
        /// <summary>
        /// Test the property 'LimiteChequeEspecial'
        /// </summary>
        [Test]
        public void LimiteChequeEspecialTest()
        {
            // TODO unit test for the property 'LimiteChequeEspecial'
        }
        /// <summary>
        /// Test the property 'TipoConta'
        /// </summary>
        [Test]
        public void TipoContaTest()
        {
            // TODO unit test for the property 'TipoConta'
        }

    }

}
