/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CpfDocumentoProposta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CpfDocumentoPropostaTests
    {
        // TODO uncomment below to declare an instance variable for CpfDocumentoProposta
        //private CpfDocumentoProposta instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CpfDocumentoProposta
            //instance = new CpfDocumentoProposta();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CpfDocumentoProposta
        /// </summary>
        [Test]
        public void CpfDocumentoPropostaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CpfDocumentoProposta
            //Assert.IsInstanceOfType<CpfDocumentoProposta> (instance, "variable 'instance' is a CpfDocumentoProposta");
        }


        /// <summary>
        /// Test the property 'Cpf'
        /// </summary>
        [Test]
        public void CpfTest()
        {
            // TODO unit test for the property 'Cpf'
        }
        /// <summary>
        /// Test the property 'Documento'
        /// </summary>
        [Test]
        public void DocumentoTest()
        {
            // TODO unit test for the property 'Documento'
        }
        /// <summary>
        /// Test the property 'Extensao'
        /// </summary>
        [Test]
        public void ExtensaoTest()
        {
            // TODO unit test for the property 'Extensao'
        }

    }

}
