/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DadoAdicional
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DadoAdicionalTests
    {
        // TODO uncomment below to declare an instance variable for DadoAdicional
        //private DadoAdicional instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DadoAdicional
            //instance = new DadoAdicional();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DadoAdicional
        /// </summary>
        [Test]
        public void DadoAdicionalInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DadoAdicional
            //Assert.IsInstanceOfType<DadoAdicional> (instance, "variable 'instance' is a DadoAdicional");
        }


        /// <summary>
        /// Test the property 'Campo'
        /// </summary>
        [Test]
        public void CampoTest()
        {
            // TODO unit test for the property 'Campo'
        }
        /// <summary>
        /// Test the property 'Valor'
        /// </summary>
        [Test]
        public void ValorTest()
        {
            // TODO unit test for the property 'Valor'
        }

    }

}
