/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DadosLiberacao
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DadosLiberacaoTests
    {
        // TODO uncomment below to declare an instance variable for DadosLiberacao
        //private DadosLiberacao instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DadosLiberacao
            //instance = new DadosLiberacao();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DadosLiberacao
        /// </summary>
        [Test]
        public void DadosLiberacaoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DadosLiberacao
            //Assert.IsInstanceOfType<DadosLiberacao> (instance, "variable 'instance' is a DadosLiberacao");
        }


        /// <summary>
        /// Test the property 'Agencia'
        /// </summary>
        [Test]
        public void AgenciaTest()
        {
            // TODO unit test for the property 'Agencia'
        }
        /// <summary>
        /// Test the property 'Banco'
        /// </summary>
        [Test]
        public void BancoTest()
        {
            // TODO unit test for the property 'Banco'
        }
        /// <summary>
        /// Test the property 'Beneficiario'
        /// </summary>
        [Test]
        public void BeneficiarioTest()
        {
            // TODO unit test for the property 'Beneficiario'
        }
        /// <summary>
        /// Test the property 'Conta'
        /// </summary>
        [Test]
        public void ContaTest()
        {
            // TODO unit test for the property 'Conta'
        }
        /// <summary>
        /// Test the property 'CpfCnpj'
        /// </summary>
        [Test]
        public void CpfCnpjTest()
        {
            // TODO unit test for the property 'CpfCnpj'
        }
        /// <summary>
        /// Test the property 'TipoContaBancaria'
        /// </summary>
        [Test]
        public void TipoContaBancariaTest()
        {
            // TODO unit test for the property 'TipoContaBancaria'
        }

    }

}
