/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DocumentoProposta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentoPropostaTests
    {
        // TODO uncomment below to declare an instance variable for DocumentoProposta
        //private DocumentoProposta instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DocumentoProposta
            //instance = new DocumentoProposta();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DocumentoProposta
        /// </summary>
        [Test]
        public void DocumentoPropostaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentoProposta
            //Assert.IsInstanceOfType<DocumentoProposta> (instance, "variable 'instance' is a DocumentoProposta");
        }


        /// <summary>
        /// Test the property 'FileContent'
        /// </summary>
        [Test]
        public void FileContentTest()
        {
            // TODO unit test for the property 'FileContent'
        }
        /// <summary>
        /// Test the property 'NomeArquivo'
        /// </summary>
        [Test]
        public void NomeArquivoTest()
        {
            // TODO unit test for the property 'NomeArquivo'
        }

    }

}
