/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Documento
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DocumentoTests
    {
        // TODO uncomment below to declare an instance variable for Documento
        //private Documento instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Documento
            //instance = new Documento();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Documento
        /// </summary>
        [Test]
        public void DocumentoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Documento
            //Assert.IsInstanceOfType<Documento> (instance, "variable 'instance' is a Documento");
        }


        /// <summary>
        /// Test the property 'Numero'
        /// </summary>
        [Test]
        public void NumeroTest()
        {
            // TODO unit test for the property 'Numero'
        }
        /// <summary>
        /// Test the property 'CodigoTipoDocumento'
        /// </summary>
        [Test]
        public void CodigoTipoDocumentoTest()
        {
            // TODO unit test for the property 'CodigoTipoDocumento'
        }
        /// <summary>
        /// Test the property 'CodigoOrgaoEmissor'
        /// </summary>
        [Test]
        public void CodigoOrgaoEmissorTest()
        {
            // TODO unit test for the property 'CodigoOrgaoEmissor'
        }
        /// <summary>
        /// Test the property 'DataEmissao'
        /// </summary>
        [Test]
        public void DataEmissaoTest()
        {
            // TODO unit test for the property 'DataEmissao'
        }
        /// <summary>
        /// Test the property 'Uf'
        /// </summary>
        [Test]
        public void UfTest()
        {
            // TODO unit test for the property 'Uf'
        }
        /// <summary>
        /// Test the property 'CodigoSegurancaCNH'
        /// </summary>
        [Test]
        public void CodigoSegurancaCNHTest()
        {
            // TODO unit test for the property 'CodigoSegurancaCNH'
        }

    }

}
