/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Emprego
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EmpregoTests
    {
        // TODO uncomment below to declare an instance variable for Emprego
        //private Emprego instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Emprego
            //instance = new Emprego();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Emprego
        /// </summary>
        [Test]
        public void EmpregoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Emprego
            //Assert.IsInstanceOfType<Emprego> (instance, "variable 'instance' is a Emprego");
        }


        /// <summary>
        /// Test the property 'NomeEmpresa'
        /// </summary>
        [Test]
        public void NomeEmpresaTest()
        {
            // TODO unit test for the property 'NomeEmpresa'
        }
        /// <summary>
        /// Test the property 'CodigoClasseProfissional'
        /// </summary>
        [Test]
        public void CodigoClasseProfissionalTest()
        {
            // TODO unit test for the property 'CodigoClasseProfissional'
        }
        /// <summary>
        /// Test the property 'CodigoAtividade'
        /// </summary>
        [Test]
        public void CodigoAtividadeTest()
        {
            // TODO unit test for the property 'CodigoAtividade'
        }
        /// <summary>
        /// Test the property 'DataAdmissao'
        /// </summary>
        [Test]
        public void DataAdmissaoTest()
        {
            // TODO unit test for the property 'DataAdmissao'
        }
        /// <summary>
        /// Test the property 'CodigoConveniada'
        /// </summary>
        [Test]
        public void CodigoConveniadaTest()
        {
            // TODO unit test for the property 'CodigoConveniada'
        }
        /// <summary>
        /// Test the property 'OrgaoConveniada'
        /// </summary>
        [Test]
        public void OrgaoConveniadaTest()
        {
            // TODO unit test for the property 'OrgaoConveniada'
        }
        /// <summary>
        /// Test the property 'NumeroBeneficio'
        /// </summary>
        [Test]
        public void NumeroBeneficioTest()
        {
            // TODO unit test for the property 'NumeroBeneficio'
        }
        /// <summary>
        /// Test the property 'EspecieBeneficio'
        /// </summary>
        [Test]
        public void EspecieBeneficioTest()
        {
            // TODO unit test for the property 'EspecieBeneficio'
        }
        /// <summary>
        /// Test the property 'MatriculaFucional'
        /// </summary>
        [Test]
        public void MatriculaFucionalTest()
        {
            // TODO unit test for the property 'MatriculaFucional'
        }
        /// <summary>
        /// Test the property 'Renda'
        /// </summary>
        [Test]
        public void RendaTest()
        {
            // TODO unit test for the property 'Renda'
        }
        /// <summary>
        /// Test the property 'Cnpj'
        /// </summary>
        [Test]
        public void CnpjTest()
        {
            // TODO unit test for the property 'Cnpj'
        }
        /// <summary>
        /// Test the property 'Telefones'
        /// </summary>
        [Test]
        public void TelefonesTest()
        {
            // TODO unit test for the property 'Telefones'
        }
        /// <summary>
        /// Test the property 'Endereco'
        /// </summary>
        [Test]
        public void EnderecoTest()
        {
            // TODO unit test for the property 'Endereco'
        }

    }

}
