/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Endereco
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EnderecoTests
    {
        // TODO uncomment below to declare an instance variable for Endereco
        //private Endereco instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Endereco
            //instance = new Endereco();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Endereco
        /// </summary>
        [Test]
        public void EnderecoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Endereco
            //Assert.IsInstanceOfType<Endereco> (instance, "variable 'instance' is a Endereco");
        }


        /// <summary>
        /// Test the property 'Logradouro'
        /// </summary>
        [Test]
        public void LogradouroTest()
        {
            // TODO unit test for the property 'Logradouro'
        }
        /// <summary>
        /// Test the property 'Numero'
        /// </summary>
        [Test]
        public void NumeroTest()
        {
            // TODO unit test for the property 'Numero'
        }
        /// <summary>
        /// Test the property 'Complemento'
        /// </summary>
        [Test]
        public void ComplementoTest()
        {
            // TODO unit test for the property 'Complemento'
        }
        /// <summary>
        /// Test the property 'Bairro'
        /// </summary>
        [Test]
        public void BairroTest()
        {
            // TODO unit test for the property 'Bairro'
        }
        /// <summary>
        /// Test the property 'Cidade'
        /// </summary>
        [Test]
        public void CidadeTest()
        {
            // TODO unit test for the property 'Cidade'
        }
        /// <summary>
        /// Test the property 'Uf'
        /// </summary>
        [Test]
        public void UfTest()
        {
            // TODO unit test for the property 'Uf'
        }
        /// <summary>
        /// Test the property 'Cep'
        /// </summary>
        [Test]
        public void CepTest()
        {
            // TODO unit test for the property 'Cep'
        }
        /// <summary>
        /// Test the property 'TempoMes'
        /// </summary>
        [Test]
        public void TempoMesTest()
        {
            // TODO unit test for the property 'TempoMes'
        }
        /// <summary>
        /// Test the property 'TempoAno'
        /// </summary>
        [Test]
        public void TempoAnoTest()
        {
            // TODO unit test for the property 'TempoAno'
        }
        /// <summary>
        /// Test the property 'TipoResidencia'
        /// </summary>
        [Test]
        public void TipoResidenciaTest()
        {
            // TODO unit test for the property 'TipoResidencia'
        }
        /// <summary>
        /// Test the property 'TipoCorrespondencia'
        /// </summary>
        [Test]
        public void TipoCorrespondenciaTest()
        {
            // TODO unit test for the property 'TipoCorrespondencia'
        }

    }

}
