/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FormaEnvio
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FormaEnvioTests
    {
        // TODO uncomment below to declare an instance variable for FormaEnvio
        //private FormaEnvio instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FormaEnvio
            //instance = new FormaEnvio();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FormaEnvio
        /// </summary>
        [Test]
        public void FormaEnvioInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FormaEnvio
            //Assert.IsInstanceOfType<FormaEnvio> (instance, "variable 'instance' is a FormaEnvio");
        }


        /// <summary>
        /// Test the property 'PorCorreio'
        /// </summary>
        [Test]
        public void PorCorreioTest()
        {
            // TODO unit test for the property 'PorCorreio'
        }
        /// <summary>
        /// Test the property 'PorEmail'
        /// </summary>
        [Test]
        public void PorEmailTest()
        {
            // TODO unit test for the property 'PorEmail'
        }
        /// <summary>
        /// Test the property 'EnderecoEmail'
        /// </summary>
        [Test]
        public void EnderecoEmailTest()
        {
            // TODO unit test for the property 'EnderecoEmail'
        }
        /// <summary>
        /// Test the property 'PorLoja'
        /// </summary>
        [Test]
        public void PorLojaTest()
        {
            // TODO unit test for the property 'PorLoja'
        }

    }

}
