/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Historico
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HistoricoTests
    {
        // TODO uncomment below to declare an instance variable for Historico
        //private Historico instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Historico
            //instance = new Historico();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Historico
        /// </summary>
        [Test]
        public void HistoricoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Historico
            //Assert.IsInstanceOfType<Historico> (instance, "variable 'instance' is a Historico");
        }


        /// <summary>
        /// Test the property 'DataObservacao'
        /// </summary>
        [Test]
        public void DataObservacaoTest()
        {
            // TODO unit test for the property 'DataObservacao'
        }
        /// <summary>
        /// Test the property 'HoraObservacao'
        /// </summary>
        [Test]
        public void HoraObservacaoTest()
        {
            // TODO unit test for the property 'HoraObservacao'
        }
        /// <summary>
        /// Test the property 'Observacao'
        /// </summary>
        [Test]
        public void ObservacaoTest()
        {
            // TODO unit test for the property 'Observacao'
        }

    }

}
