/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InclusaoPropostaResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InclusaoPropostaResponseTests
    {
        // TODO uncomment below to declare an instance variable for InclusaoPropostaResponse
        //private InclusaoPropostaResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InclusaoPropostaResponse
            //instance = new InclusaoPropostaResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InclusaoPropostaResponse
        /// </summary>
        [Test]
        public void InclusaoPropostaResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InclusaoPropostaResponse
            //Assert.IsInstanceOfType<InclusaoPropostaResponse> (instance, "variable 'instance' is a InclusaoPropostaResponse");
        }


        /// <summary>
        /// Test the property 'Numero'
        /// </summary>
        [Test]
        public void NumeroTest()
        {
            // TODO unit test for the property 'Numero'
        }
        /// <summary>
        /// Test the property 'Situacao'
        /// </summary>
        [Test]
        public void SituacaoTest()
        {
            // TODO unit test for the property 'Situacao'
        }

    }

}
