/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Oferta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OfertaTests
    {
        // TODO uncomment below to declare an instance variable for Oferta
        //private Oferta instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Oferta
            //instance = new Oferta();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Oferta
        /// </summary>
        [Test]
        public void OfertaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Oferta
            //Assert.IsInstanceOfType<Oferta> (instance, "variable 'instance' is a Oferta");
        }


        /// <summary>
        /// Test the property 'IdOferta'
        /// </summary>
        [Test]
        public void IdOfertaTest()
        {
            // TODO unit test for the property 'IdOferta'
        }
        /// <summary>
        /// Test the property 'OrigemOferta'
        /// </summary>
        [Test]
        public void OrigemOfertaTest()
        {
            // TODO unit test for the property 'OrigemOferta'
        }
        /// <summary>
        /// Test the property 'DataVencimentoPrimeiraParcela'
        /// </summary>
        [Test]
        public void DataVencimentoPrimeiraParcelaTest()
        {
            // TODO unit test for the property 'DataVencimentoPrimeiraParcela'
        }
        /// <summary>
        /// Test the property 'DataVencimentoUltimaParcela'
        /// </summary>
        [Test]
        public void DataVencimentoUltimaParcelaTest()
        {
            // TODO unit test for the property 'DataVencimentoUltimaParcela'
        }
        /// <summary>
        /// Test the property 'CetAnual'
        /// </summary>
        [Test]
        public void CetAnualTest()
        {
            // TODO unit test for the property 'CetAnual'
        }
        /// <summary>
        /// Test the property 'CetMensal'
        /// </summary>
        [Test]
        public void CetMensalTest()
        {
            // TODO unit test for the property 'CetMensal'
        }
        /// <summary>
        /// Test the property 'DataMovimento'
        /// </summary>
        [Test]
        public void DataMovimentoTest()
        {
            // TODO unit test for the property 'DataMovimento'
        }
        /// <summary>
        /// Test the property 'CodigoPlano'
        /// </summary>
        [Test]
        public void CodigoPlanoTest()
        {
            // TODO unit test for the property 'CodigoPlano'
        }
        /// <summary>
        /// Test the property 'DescricaoPlano'
        /// </summary>
        [Test]
        public void DescricaoPlanoTest()
        {
            // TODO unit test for the property 'DescricaoPlano'
        }
        /// <summary>
        /// Test the property 'CodigoProduto'
        /// </summary>
        [Test]
        public void CodigoProdutoTest()
        {
            // TODO unit test for the property 'CodigoProduto'
        }
        /// <summary>
        /// Test the property 'DescricaoProduto'
        /// </summary>
        [Test]
        public void DescricaoProdutoTest()
        {
            // TODO unit test for the property 'DescricaoProduto'
        }
        /// <summary>
        /// Test the property 'DataEmissao'
        /// </summary>
        [Test]
        public void DataEmissaoTest()
        {
            // TODO unit test for the property 'DataEmissao'
        }
        /// <summary>
        /// Test the property 'FinanciadoIndice'
        /// </summary>
        [Test]
        public void FinanciadoIndiceTest()
        {
            // TODO unit test for the property 'FinanciadoIndice'
        }
        /// <summary>
        /// Test the property 'FinioFSeguro'
        /// </summary>
        [Test]
        public void FinioFSeguroTest()
        {
            // TODO unit test for the property 'FinioFSeguro'
        }
        /// <summary>
        /// Test the property 'IdProdutoSeguro'
        /// </summary>
        [Test]
        public void IdProdutoSeguroTest()
        {
            // TODO unit test for the property 'IdProdutoSeguro'
        }
        /// <summary>
        /// Test the property 'ValorIOF'
        /// </summary>
        [Test]
        public void ValorIOFTest()
        {
            // TODO unit test for the property 'ValorIOF'
        }
        /// <summary>
        /// Test the property 'Prazo'
        /// </summary>
        [Test]
        public void PrazoTest()
        {
            // TODO unit test for the property 'Prazo'
        }
        /// <summary>
        /// Test the property 'ValorPrimeiraPrestacao'
        /// </summary>
        [Test]
        public void ValorPrimeiraPrestacaoTest()
        {
            // TODO unit test for the property 'ValorPrimeiraPrestacao'
        }
        /// <summary>
        /// Test the property 'Seguradora'
        /// </summary>
        [Test]
        public void SeguradoraTest()
        {
            // TODO unit test for the property 'Seguradora'
        }
        /// <summary>
        /// Test the property 'Seguro'
        /// </summary>
        [Test]
        public void SeguroTest()
        {
            // TODO unit test for the property 'Seguro'
        }
        /// <summary>
        /// Test the property 'ValorTAC'
        /// </summary>
        [Test]
        public void ValorTACTest()
        {
            // TODO unit test for the property 'ValorTAC'
        }
        /// <summary>
        /// Test the property 'ValorTaxa'
        /// </summary>
        [Test]
        public void ValorTaxaTest()
        {
            // TODO unit test for the property 'ValorTaxa'
        }
        /// <summary>
        /// Test the property 'ValorTaxaAnual'
        /// </summary>
        [Test]
        public void ValorTaxaAnualTest()
        {
            // TODO unit test for the property 'ValorTaxaAnual'
        }
        /// <summary>
        /// Test the property 'ValorCompra'
        /// </summary>
        [Test]
        public void ValorCompraTest()
        {
            // TODO unit test for the property 'ValorCompra'
        }
        /// <summary>
        /// Test the property 'ValorCredito'
        /// </summary>
        [Test]
        public void ValorCreditoTest()
        {
            // TODO unit test for the property 'ValorCredito'
        }
        /// <summary>
        /// Test the property 'ValorFinanciado'
        /// </summary>
        [Test]
        public void ValorFinanciadoTest()
        {
            // TODO unit test for the property 'ValorFinanciado'
        }
        /// <summary>
        /// Test the property 'ValorLiberado'
        /// </summary>
        [Test]
        public void ValorLiberadoTest()
        {
            // TODO unit test for the property 'ValorLiberado'
        }
        /// <summary>
        /// Test the property 'ValorLiquidar'
        /// </summary>
        [Test]
        public void ValorLiquidarTest()
        {
            // TODO unit test for the property 'ValorLiquidar'
        }
        /// <summary>
        /// Test the property 'ValorParcela'
        /// </summary>
        [Test]
        public void ValorParcelaTest()
        {
            // TODO unit test for the property 'ValorParcela'
        }
        /// <summary>
        /// Test the property 'ValorSeguro'
        /// </summary>
        [Test]
        public void ValorSeguroTest()
        {
            // TODO unit test for the property 'ValorSeguro'
        }
        /// <summary>
        /// Test the property 'ValorTaxaInclusao'
        /// </summary>
        [Test]
        public void ValorTaxaInclusaoTest()
        {
            // TODO unit test for the property 'ValorTaxaInclusao'
        }
        /// <summary>
        /// Test the property 'ValorTaxaRenovacao'
        /// </summary>
        [Test]
        public void ValorTaxaRenovacaoTest()
        {
            // TODO unit test for the property 'ValorTaxaRenovacao'
        }
        /// <summary>
        /// Test the property 'ValorTotal'
        /// </summary>
        [Test]
        public void ValorTotalTest()
        {
            // TODO unit test for the property 'ValorTotal'
        }
        /// <summary>
        /// Test the property 'ValorTotalPST'
        /// </summary>
        [Test]
        public void ValorTotalPSTTest()
        {
            // TODO unit test for the property 'ValorTotalPST'
        }
        /// <summary>
        /// Test the property 'ExpiradaFaixaTarifaInclusao'
        /// </summary>
        [Test]
        public void ExpiradaFaixaTarifaInclusaoTest()
        {
            // TODO unit test for the property 'ExpiradaFaixaTarifaInclusao'
        }
        /// <summary>
        /// Test the property 'SugeridoFaixaRetorno'
        /// </summary>
        [Test]
        public void SugeridoFaixaRetornoTest()
        {
            // TODO unit test for the property 'SugeridoFaixaRetorno'
        }
        /// <summary>
        /// Test the property 'TipoSimulacao'
        /// </summary>
        [Test]
        public void TipoSimulacaoTest()
        {
            // TODO unit test for the property 'TipoSimulacao'
        }

    }

}
