/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Pendencia
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PendenciaTests
    {
        // TODO uncomment below to declare an instance variable for Pendencia
        //private Pendencia instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Pendencia
            //instance = new Pendencia();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Pendencia
        /// </summary>
        [Test]
        public void PendenciaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Pendencia
            //Assert.IsInstanceOfType<Pendencia> (instance, "variable 'instance' is a Pendencia");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Descricao'
        /// </summary>
        [Test]
        public void DescricaoTest()
        {
            // TODO unit test for the property 'Descricao'
        }
        /// <summary>
        /// Test the property 'Parecer'
        /// </summary>
        [Test]
        public void ParecerTest()
        {
            // TODO unit test for the property 'Parecer'
        }

    }

}
