/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PreEfetivacaoPropostaRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PreEfetivacaoPropostaRequestTests
    {
        // TODO uncomment below to declare an instance variable for PreEfetivacaoPropostaRequest
        //private PreEfetivacaoPropostaRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PreEfetivacaoPropostaRequest
            //instance = new PreEfetivacaoPropostaRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PreEfetivacaoPropostaRequest
        /// </summary>
        [Test]
        public void PreEfetivacaoPropostaRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PreEfetivacaoPropostaRequest
            //Assert.IsInstanceOfType<PreEfetivacaoPropostaRequest> (instance, "variable 'instance' is a PreEfetivacaoPropostaRequest");
        }


        /// <summary>
        /// Test the property 'Cheques'
        /// </summary>
        [Test]
        public void ChequesTest()
        {
            // TODO unit test for the property 'Cheques'
        }
        /// <summary>
        /// Test the property 'DadosLiberacao'
        /// </summary>
        [Test]
        public void DadosLiberacaoTest()
        {
            // TODO unit test for the property 'DadosLiberacao'
        }
        /// <summary>
        /// Test the property 'FormaEnvio'
        /// </summary>
        [Test]
        public void FormaEnvioTest()
        {
            // TODO unit test for the property 'FormaEnvio'
        }
        /// <summary>
        /// Test the property 'TipoEfetivacao'
        /// </summary>
        [Test]
        public void TipoEfetivacaoTest()
        {
            // TODO unit test for the property 'TipoEfetivacao'
        }

    }

}
