/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PreProposta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PrePropostaTests
    {
        // TODO uncomment below to declare an instance variable for PreProposta
        //private PreProposta instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PreProposta
            //instance = new PreProposta();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PreProposta
        /// </summary>
        [Test]
        public void PrePropostaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PreProposta
            //Assert.IsInstanceOfType<PreProposta> (instance, "variable 'instance' is a PreProposta");
        }


        /// <summary>
        /// Test the property 'Operador'
        /// </summary>
        [Test]
        public void OperadorTest()
        {
            // TODO unit test for the property 'Operador'
        }
        /// <summary>
        /// Test the property 'CodigoProduto'
        /// </summary>
        [Test]
        public void CodigoProdutoTest()
        {
            // TODO unit test for the property 'CodigoProduto'
        }
        /// <summary>
        /// Test the property 'ValorCompra'
        /// </summary>
        [Test]
        public void ValorCompraTest()
        {
            // TODO unit test for the property 'ValorCompra'
        }
        /// <summary>
        /// Test the property 'ValorPrestacao'
        /// </summary>
        [Test]
        public void ValorPrestacaoTest()
        {
            // TODO unit test for the property 'ValorPrestacao'
        }
        /// <summary>
        /// Test the property 'PrazoPagamento'
        /// </summary>
        [Test]
        public void PrazoPagamentoTest()
        {
            // TODO unit test for the property 'PrazoPagamento'
        }
        /// <summary>
        /// Test the property 'TipoSeguro'
        /// </summary>
        [Test]
        public void TipoSeguroTest()
        {
            // TODO unit test for the property 'TipoSeguro'
        }
        /// <summary>
        /// Test the property 'DataVencimentoPrimeiraParcela'
        /// </summary>
        [Test]
        public void DataVencimentoPrimeiraParcelaTest()
        {
            // TODO unit test for the property 'DataVencimentoPrimeiraParcela'
        }
        /// <summary>
        /// Test the property 'Candidato'
        /// </summary>
        [Test]
        public void CandidatoTest()
        {
            // TODO unit test for the property 'Candidato'
        }

    }

}
