/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Proposta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PropostaTests
    {
        // TODO uncomment below to declare an instance variable for Proposta
        //private Proposta instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Proposta
            //instance = new Proposta();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Proposta
        /// </summary>
        [Test]
        public void PropostaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Proposta
            //Assert.IsInstanceOfType<Proposta> (instance, "variable 'instance' is a Proposta");
        }


        /// <summary>
        /// Test the property 'Numero'
        /// </summary>
        [Test]
        public void NumeroTest()
        {
            // TODO unit test for the property 'Numero'
        }
        /// <summary>
        /// Test the property 'DataEmissao'
        /// </summary>
        [Test]
        public void DataEmissaoTest()
        {
            // TODO unit test for the property 'DataEmissao'
        }
        /// <summary>
        /// Test the property 'DataVencimentoPrimeiraParcela'
        /// </summary>
        [Test]
        public void DataVencimentoPrimeiraParcelaTest()
        {
            // TODO unit test for the property 'DataVencimentoPrimeiraParcela'
        }
        /// <summary>
        /// Test the property 'CodigoProduto'
        /// </summary>
        [Test]
        public void CodigoProdutoTest()
        {
            // TODO unit test for the property 'CodigoProduto'
        }
        /// <summary>
        /// Test the property 'CodigoPlanoPagamento'
        /// </summary>
        [Test]
        public void CodigoPlanoPagamentoTest()
        {
            // TODO unit test for the property 'CodigoPlanoPagamento'
        }
        /// <summary>
        /// Test the property 'PrazoPagamento'
        /// </summary>
        [Test]
        public void PrazoPagamentoTest()
        {
            // TODO unit test for the property 'PrazoPagamento'
        }
        /// <summary>
        /// Test the property 'CodigoMidia'
        /// </summary>
        [Test]
        public void CodigoMidiaTest()
        {
            // TODO unit test for the property 'CodigoMidia'
        }
        /// <summary>
        /// Test the property 'TipoContrato'
        /// </summary>
        [Test]
        public void TipoContratoTest()
        {
            // TODO unit test for the property 'TipoContrato'
        }
        /// <summary>
        /// Test the property 'ValorCompra'
        /// </summary>
        [Test]
        public void ValorCompraTest()
        {
            // TODO unit test for the property 'ValorCompra'
        }
        /// <summary>
        /// Test the property 'ValorEntrada'
        /// </summary>
        [Test]
        public void ValorEntradaTest()
        {
            // TODO unit test for the property 'ValorEntrada'
        }
        /// <summary>
        /// Test the property 'ValorPrestacao'
        /// </summary>
        [Test]
        public void ValorPrestacaoTest()
        {
            // TODO unit test for the property 'ValorPrestacao'
        }
        /// <summary>
        /// Test the property 'ValorLiberado'
        /// </summary>
        [Test]
        public void ValorLiberadoTest()
        {
            // TODO unit test for the property 'ValorLiberado'
        }
        /// <summary>
        /// Test the property 'DadosAdicionais'
        /// </summary>
        [Test]
        public void DadosAdicionaisTest()
        {
            // TODO unit test for the property 'DadosAdicionais'
        }
        /// <summary>
        /// Test the property 'TipoSeguro'
        /// </summary>
        [Test]
        public void TipoSeguroTest()
        {
            // TODO unit test for the property 'TipoSeguro'
        }
        /// <summary>
        /// Test the property 'Clientes'
        /// </summary>
        [Test]
        public void ClientesTest()
        {
            // TODO unit test for the property 'Clientes'
        }
        /// <summary>
        /// Test the property 'Cheques'
        /// </summary>
        [Test]
        public void ChequesTest()
        {
            // TODO unit test for the property 'Cheques'
        }
        /// <summary>
        /// Test the property 'FormaEnvio'
        /// </summary>
        [Test]
        public void FormaEnvioTest()
        {
            // TODO unit test for the property 'FormaEnvio'
        }
        /// <summary>
        /// Test the property 'DadosLiberacao'
        /// </summary>
        [Test]
        public void DadosLiberacaoTest()
        {
            // TODO unit test for the property 'DadosLiberacao'
        }
        /// <summary>
        /// Test the property 'TipoEfetivacao'
        /// </summary>
        [Test]
        public void TipoEfetivacaoTest()
        {
            // TODO unit test for the property 'TipoEfetivacao'
        }

    }

}
