/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PropostaResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PropostaResponseTests
    {
        // TODO uncomment below to declare an instance variable for PropostaResponse
        //private PropostaResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PropostaResponse
            //instance = new PropostaResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PropostaResponse
        /// </summary>
        [Test]
        public void PropostaResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PropostaResponse
            //Assert.IsInstanceOfType<PropostaResponse> (instance, "variable 'instance' is a PropostaResponse");
        }


        /// <summary>
        /// Test the property 'Numero'
        /// </summary>
        [Test]
        public void NumeroTest()
        {
            // TODO unit test for the property 'Numero'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'CodigoLoja'
        /// </summary>
        [Test]
        public void CodigoLojaTest()
        {
            // TODO unit test for the property 'CodigoLoja'
        }
        /// <summary>
        /// Test the property 'CodigoLojista'
        /// </summary>
        [Test]
        public void CodigoLojistaTest()
        {
            // TODO unit test for the property 'CodigoLojista'
        }
        /// <summary>
        /// Test the property 'CodigoProduto'
        /// </summary>
        [Test]
        public void CodigoProdutoTest()
        {
            // TODO unit test for the property 'CodigoProduto'
        }
        /// <summary>
        /// Test the property 'Valor'
        /// </summary>
        [Test]
        public void ValorTest()
        {
            // TODO unit test for the property 'Valor'
        }
        /// <summary>
        /// Test the property 'Tipo'
        /// </summary>
        [Test]
        public void TipoTest()
        {
            // TODO unit test for the property 'Tipo'
        }
        /// <summary>
        /// Test the property 'Situacao'
        /// </summary>
        [Test]
        public void SituacaoTest()
        {
            // TODO unit test for the property 'Situacao'
        }

    }

}
