/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReferenciaPessoal
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReferenciaPessoalTests
    {
        // TODO uncomment below to declare an instance variable for ReferenciaPessoal
        //private ReferenciaPessoal instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReferenciaPessoal
            //instance = new ReferenciaPessoal();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReferenciaPessoal
        /// </summary>
        [Test]
        public void ReferenciaPessoalInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReferenciaPessoal
            //Assert.IsInstanceOfType<ReferenciaPessoal> (instance, "variable 'instance' is a ReferenciaPessoal");
        }


        /// <summary>
        /// Test the property 'Nome'
        /// </summary>
        [Test]
        public void NomeTest()
        {
            // TODO unit test for the property 'Nome'
        }
        /// <summary>
        /// Test the property 'Relacionamento'
        /// </summary>
        [Test]
        public void RelacionamentoTest()
        {
            // TODO unit test for the property 'Relacionamento'
        }
        /// <summary>
        /// Test the property 'Telefone'
        /// </summary>
        [Test]
        public void TelefoneTest()
        {
            // TODO unit test for the property 'Telefone'
        }

    }

}
