/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StatusPropostaResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StatusPropostaResponseTests
    {
        // TODO uncomment below to declare an instance variable for StatusPropostaResponse
        //private StatusPropostaResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StatusPropostaResponse
            //instance = new StatusPropostaResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StatusPropostaResponse
        /// </summary>
        [Test]
        public void StatusPropostaResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StatusPropostaResponse
            //Assert.IsInstanceOfType<StatusPropostaResponse> (instance, "variable 'instance' is a StatusPropostaResponse");
        }


        /// <summary>
        /// Test the property 'DescricaoSituacao'
        /// </summary>
        [Test]
        public void DescricaoSituacaoTest()
        {
            // TODO unit test for the property 'DescricaoSituacao'
        }

    }

}
