/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Telefone
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TelefoneTests
    {
        // TODO uncomment below to declare an instance variable for Telefone
        //private Telefone instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Telefone
            //instance = new Telefone();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Telefone
        /// </summary>
        [Test]
        public void TelefoneInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Telefone
            //Assert.IsInstanceOfType<Telefone> (instance, "variable 'instance' is a Telefone");
        }


        /// <summary>
        /// Test the property 'Tipo'
        /// </summary>
        [Test]
        public void TipoTest()
        {
            // TODO unit test for the property 'Tipo'
        }
        /// <summary>
        /// Test the property 'Ddd'
        /// </summary>
        [Test]
        public void DddTest()
        {
            // TODO unit test for the property 'Ddd'
        }
        /// <summary>
        /// Test the property 'Numero'
        /// </summary>
        [Test]
        public void NumeroTest()
        {
            // TODO unit test for the property 'Numero'
        }
        /// <summary>
        /// Test the property 'Ramal'
        /// </summary>
        [Test]
        public void RamalTest()
        {
            // TODO unit test for the property 'Ramal'
        }

    }

}
