/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TipoSimulacao
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TipoSimulacaoTests
    {
        // TODO uncomment below to declare an instance variable for TipoSimulacao
        //private TipoSimulacao instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TipoSimulacao
            //instance = new TipoSimulacao();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TipoSimulacao
        /// </summary>
        [Test]
        public void TipoSimulacaoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TipoSimulacao
            //Assert.IsInstanceOfType<TipoSimulacao> (instance, "variable 'instance' is a TipoSimulacao");
        }



    }

}
