/* 
 * Gestão de Propostas
 *
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TipoSeguro
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TipoSeguroTests
    {
        // TODO uncomment below to declare an instance variable for TipoSeguro
        //private TipoSeguro instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TipoSeguro
            //instance = new TipoSeguro();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TipoSeguro
        /// </summary>
        [Test]
        public void TipoSeguroInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TipoSeguro
            //Assert.IsInstanceOfType<TipoSeguro> (instance, "variable 'instance' is a TipoSeguro");
        }



    }

}
